#define UNKNOWN 0 
#define RELOP 1
#define CHAR_CONST 2
#define REAL_CONST 3 
#define INTEGER_CONST 4
#define IDENTIFIER 5
#define BOOL_CONST 6
#define FUNC 7
#define MULOP 8
#define ADDOP 9
#define PROGRAM 10
#define CHAR_TYPE 11
#define BOOL_TYPE 12
#define REAL_TYPE 13
#define INTEGER_TYPE 14
#define NOT_TOKEN 15
#define GOTO_TOKEN 16
#define WRITE_TOKEN 17
#define READ_TOKEN 18
#define UNTIL_TOKEN 19
#define WHILE_TOKEN 20
#define DO_TOKEN 21
#define END_TOKEN 22
#define BEGIN_TOKEN 23
#define ELSE_TOKEN 24
#define THEN_TOKEN 25
#define IF_TOKEN 26
#define SEMICOLON 27
#define COLON 28
#define COMMA 29
#define ASSIGN 30
#define OPEN_P 31
#define CLOSE_P 32