#define UNKNOWN 0 
#define RELOP 1
#define CHAR_CONST 2
#define CONST 3
#define IDENTIFIER 4
#define BOOL_CONST 5
#define FUNC 6
#define MULOP 7
#define ADDOP 8
#define PROGRAM 9
#define CHAR_TYPE 10
#define BOOL_TYPE 11
#define REAL_TYPE 12
#define INTEGER_TYPE 13
#define NOT_TOKEN 14
#define GOTO_TOKEN 15
#define WRITE_TOKEN 16
#define READ_TOKEN 17
#define UNTIL_TOKEN 18
#define WHILE_TOKEN 19
#define DO_TOKEN 20
#define END_TOKEN 21
#define BEGIN_TOKEN 22
#define ELSE_TOKEN 23
#define THEN_TOKEN 24
#define IF_TOKEN 25
#define SEMICOLON 26
#define COLON 27
#define COMMA 28
#define ASSIGN 29
#define OPEN_P 30
#define CLOSE_P 31
